### PR TITLE
primus client connect event is 'open'

### PR DESCRIPTION
**Pull request by ahdinosaur**
see https://github.com/primus/primus#events

### CODE REVIEW

**Comment by daffl** [comment]
Thank you! I was wondering about that actually. Do you have an idea why the Primus tests was passing before?

**Comment by ekryski** [comment]
@ahdinosaur good catch. I totally missed that when I review the PR. That's weird that those tests were passing. We'll need to look at that. This is good to merge though.

**Comment by ahdinosaur** [comment]
@daffl is it because [the tests only run after the 'open' event](https://github.com/feathersjs/feathers-authentication/blob/master/test/integration/primus.test.js#L46-L51)?

**Comment by daffl** [comment]
Oh. Haha, well that'll do it. I thought it was timing out but it was totally a workaround for that bug. I'm pretty sure we can take that out now.

**Pull request merged**
