### PR TITLE
Fixed bug in restrictToOwner

### PR DESCRIPTION
**Pull request by thosakwe**
See issue [#175](https://github.com/feathersjs/feathers-authentication/issues/175).

### CODE REVIEW

**Comment by daffl** [comment]
This looks like a good fix but `npm test` is failing for that hook now.

**Comment by ekryski** [comment]
Thanks for the PR @thosakwe! Unfortunately I don't think it's the right fix. Currently the hook assumes `hook.id` is present. Only changing the error check will just cause the hook to [fail later on](https://github.com/feathersjs/feathers-authentication/blob/master/src/hooks/restrict-to-owner.js#L44) by returning a 404.

I actually think it is very valid that is throws an error on mass deletion. If you want to support mass deletion then I think there are 3 different options:

- you should use a custom hook
- use the `restrictToRoles` hook and set a user role that has access to do mass deletions
- we should support an optional callback to determine when the hook should execute, like we do in the other bundled hooks (see [here](http://docs.feathersjs.com/hooks/bundled.html#disable))

In order to determine whether you have access to items you want to modify you need to look them up first, this could be incredibly expensive if you did a blank find on all items for the service. So in reality, I think what you are looking for is to conditionally disable or enable this hook based on some condition.

**Comment by thosakwe** [comment]
Ah, I see.

And on second though, my fix might have been a bit ill-advised, too. Not sure if it would be a good to tell [feathers-seeder](https://github.com/thosakwe/feathers-seeder) users, "Hey! To use this plug-in, you have to remove this security feature from your application."

**Comment by ekryski** [comment]
@thosakwe well, like I said you can just change your hooks or put in the readme for feathers-seeder that you do need to change the hook.

It sounds like the more ideal solution is to allow conditional running of the hooks.

**Comment by ekryski** [comment]
I'm going to close this as I think we should support conditionally running hooks. I've created #210 to track that.

**Comment by shadowRR** [comment]
I agree about the fix, but this hook isn't returning the proper error. 

It should handle both case, when you are on the wrong hook method, and when the id is missing. Otherwise, you can loose some time trying to figure out why feathers tells you you're using the hook on the wrong method, while it isn't the case.

**Comment by UlyssesAlves** [comment]
I don't know if it's related, but I'm receiving an error saying **The 'restrictToOwner' hook should only be used on the 'get', 'update', 'patch' and 'remove' service methods.**. This error ocurs when I try to search for a user by id inside a middleware funcion:

`app.get('/notificacoes/email/alteracao-de-senha/:idUsuario/:idSolicitacao', notificacoes.processeSolicitacaoDeAlteracaoDeSenha);`

servicoDeUsuarios.get(idUsuario)
            .then(usuario => {
                  // code here is not run
             });
             catch(error => {
                  // code enters inside this error handler with the above said message.
             });

What is wrong with this code, please?

**Pull request closed without merging**
