### PR TITLE
Customize the JWT payload

### PR DESCRIPTION
**Pull request by enten**
PR to implements JWT payload customization #78 

Add a new option `extraFields` which requires an array of field names (corresponding to the fields of the `userEndpoint` service).

### Usage

```javascript
// default.json
{
  "auth": {
    "extraFields": [
      "email",
      "roles"
    ]
  }
}

// create token
// $ curl http://localhost:3030/auth/local
//      -X POST
//      -H 'Accept: application/json' 
//      -H 'Content-type: application/json' 
//      -d '{"email": "steven@enten.fr", "password":"pass"}'
{
  "email": "steven@enten.fr",
  "roles": [
    "admin"
  ],
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjUyYjEzNDUwLTRjMzEtNDA4Yi04OWU5LWMxMzkxYTk1N2Q5MiIsImVtYWlsIjoic3RldmVuQGVudGVuLmZyIiwicm9sZXMiOlsiYWRtaW4iXSwiaWF0IjoxNDU2MzkxMTUzLCJleHAiOjE0NTY0Nzc1NTMsImlzcyI6ImZlYXRoZXJzIn0.VWUOUS4wjGDiQ4wXYyiQfxt8YOaSD6kWB6je-OpAneo",
  "data": {
    "id": "52b13450-4c31-408b-89e9-c1391a957d92",
    "email": "steven@enten.fr",
    "roles": [
      "admin"
    ],
    "profile": {
      "foo": "bar"
    },
    "activated": false,
    "activation_token": "IgaifUlghYXQ",
    "created_at": "2016-02-24T23:19:34.158Z",
    "updated_at": "2016-02-24T23:20:43.337Z",
    "deleted_at": null
  }
}

// decrypted token
{
  "id": "52b13450-4c31-408b-89e9-c1391a957d92",
  "email": "steven@enten.fr",
  "roles": [
    "admin"
  ],
  "iat": 1456391153,
  "exp": 1456477553,
  "iss": "feathers"
}

// refresh token
// $ curl http://localhost:3030/auth/token/refresh
//      -X GET
//      -H 'Accept: application/json'
//      -H 'Content-type: application/json'
//      -H'Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjUyYjEzNDUwLTRjMzEtNDA4Yi04OWU5LWMxMzkxYTk1N2Q5MiIsImVtYWlsIjoic3RldmVuQGVudGVuLmZyIiwicm9sZXMiOlsiYWRtaW4iXSwiaWF0IjoxNDU2MzkxMTUzLCJleHAiOjE0NTY0Nzc1NTMsImlzcyI6ImZlYXRoZXJzIn0.VWUOUS4wjGDiQ4wXYyiQfxt8YOaSD6kWB6je-OpAneo'
{
  "email": "steven@enten.fr",
  "roles": [
    "admin"
  ],
  "iat": 1456391153,
  "exp": 1456477553,
  "iss": "feathers",
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjUyYjEzNDUwLTRjMzEtNDA4Yi04OWU5LWMxMzkxYTk1N2Q5MiIsImVtYWlsIjoic3RldmVuQGVudGVuLmZyIiwicm9sZXMiOlsiYWRtaW4iXSwiaWF0IjoxNDU2MzkxMTUzLCJleHAiOjE0NTY0Nzc3NzAsImlzcyI6ImZlYXRoZXJzIn0.838omN2kACyWU5uR-NSjfMfjtXFxAV1V8ol48IRgRIQ",
  "data": {
    "id": "52b13450-4c31-408b-89e9-c1391a957d92",
    "email": "steven@enten.fr",
    "roles": [
      "admin"
    ],
    "profile": {
      "foo": "bar"
    },
    "activated": false,
    "activation_token": "IgaifUlghYXQ",
    "created_at": "2016-02-24T23:19:34.158Z",
    "updated_at": "2016-02-24T23:20:43.337Z",
    "deleted_at": null
  }
}

// decrypted token
{
  "id": "52b13450-4c31-408b-89e9-c1391a957d92",
  "email": "steven@enten.fr",
  "roles": [
    "admin"
  ],
  "iat": 1456391153,
  "exp": 1456477770,
  "iss": "feathers"
}






 
```

### CODE REVIEW

**Comment by ekryski** [comment]
@enten I haven't forgotten about this. We've just been super busy. Will get to it in a couple days.

**Comment by ekryski** [comment]
@enten sorry about this but do you mind resolving the merge conflicts? This looks good and I'm writing tests today. When you do I'll merge it in right away and hopefully get a release out by tomorrow.

**Comment by enten** [comment]
The conflict was in `README.md`.

**Comment by ekryski** [comment]
Whoop! Thanks!

**Comment by enten** [comment]
Sorry. I made a mistake in [README changelog](https://github.com/feathersjs/feathers-authentication#changelog).

You need to remove `<<<<<<< HEAD` line.

**Comment by ekryski** [comment]
No problemo! Fixed it.

**Pull request merged**
