### PR TITLE
Adding passwordless service

### PR DESCRIPTION
**Pull request by ccummings**
Adds passwordless auth via the [passwordless](https://passwordless.net/) library.

This is setup to work stateless without sessions to match the rest of feather's auth, but that can be enabled with the `sessionSupport` middleware if needed in the future.

Authentication flow works like this:

- User submits email address to `auth/passwordless`
    - If the user is new, create user
    - Generate a token and deliver it using the various delivery methods (email, sms, carrier pigeon)
- User clicks the link they were given which should `GET auth/passwordless`
    - We validate the token and return a JWT token (using the token service)

At this point, all auth is done with the JWT token.

I've added a `passwordless` service and made a few adjustments to the middleware. I also created an example which works for authenticating.

It seems the feathers client stuff around authentication and authorization is not working right now (retrieving messages throws errors), but the service itself is modeled closely after `local` and `token` so when that is sorted, this should work just fine.

### CODE REVIEW

**Comment by ekryski** [comment]
Holy :hankey: @ccummings! This looks great! I'll take a look at this today and hopefully get it merged in pretty quickly.

**Comment by ekryski** [comment]
This would close #7 and probably #5.

**Comment by daffl** [comment]
There are some timeouts in the tests. Not sure why those are happening.

**Comment by ccummings** [comment]
After playing with this a bit more, I'm not sure the `passwordless` library is the best fit. It does some odd things like closing the response so you get "headers already sent" errors.

Something like this could be made more composable so it could be used in a number of different schemes. to do that it should:
- Generate different kinds of tokens (algorithmic, simple pin codes, etc)
- Store them using existing feathers DB adapters
- Deliver them via email, sms, etc using feathers service plugins
- verify tokens and redirect to other services

This would enable the normal passwordless flow (link in email), multi factor auth (pin code to SMS or code to email after a local auth) or could be used for generating tokens for forgotten passwords.

Still trying to sort out exactly how this would look, open to suggestions.

**Comment by ekryski** [comment]
@ccummings that was my thought when skimming it that it was doing a lot more than we need. You nailed exactly what I've been thinking. I think it's actually pretty easy. I'm going to be digging into auth again today so I will push a PR tonight/tomorrow for this functionality.

**Comment by jonjamz** [comment]
Excited for this feature!

**Comment by daffl** [comment]
Did we reach a verdict on this?

**Comment by ekryski** [comment]
I think we've agreed that using passwordless isn't the right solution because it does a lot more than we need. That being said I'd like to leave it open for reference until I get my PR up. Hopefully in the next couple days busy with some other stuff at the moment.

**Comment by ccummings** [comment]
This is much better off being written from the ground up using services and middleware instead of trying to shoehorn an existing middleware solution which doesn't seem to play nice with other middleware.

@ekryski I'd be happy to help out on this if you have a branch in the works.

**Comment by daffl** [comment]
Sounds good. Glad everybody agrees. I'm going to close this PR then. Thanks again for adding this @ccummings, hopefully we can iterate to the final version.

**Pull request closed without merging**
