### PR TITLE
Fixing client query

### PR DESCRIPTION
**Pull request by fastlorenzo**
Fixing issue #64

### CODE REVIEW

**Comment by ekryski** [comment]
It looks good. I've got some changes coming in a PR that does the same thing plus some others on the back end side that you are probably unaware of and also adds some tests. Just give me another 15 minutes or so.

**Comment by ekryski** [comment]
Thanks so much for your help @fastlorenzo! I'm going to close this in favour of #67 because there is actually a bit more than needed to happen to clean up dead code and I thought it would be faster if I just do it rather than explaining everything that needed to be removed and why.

**Comment by ekryski** [comment]
Fuck it. I'll merge it to give credit where it is due. Thanks @fastlorenzo!

**Comment by marshallswain** [comment]
Atta boy!  :)

**Comment by fastlorenzo** [comment]
Haha thanks @ekryski

**Pull request merged**
