### PR TITLE
Creates better way or returning data in a familiar format

### PR DESCRIPTION
**Pull request by codingfriend1**
Supports consistent pagination with the rest of the app. Returns one item if using get and an array of items if using find even if the array has only one item.

### CODE REVIEW

**Comment by ekryski** [comment]
@codingfriend1 thanks! Can you resolve conflicts and provide a brief description of what this is doing?

**Comment by codingfriend1** [comment]
Merge conflicts fixed!

**Comment by kristianmandrup** [comment]
Please merge and describe changes :)

**Comment by codingfriend1** [comment]
Done.

**Comment by ekryski** [comment]
Whoop! Whoop! Thanks @codingfriend1!

**Comment by kristianmandrup** [comment]
Awesome guys :)

**Pull request merged**
