### PR TITLE
Manually supply an endpoint to the Client authenticate() method

### PR DESCRIPTION
**Pull request by mcnamee**
By simply providing the ability to specify the endpoint in the client authenticate method, it allows the ability for mobile users to authenticate via a native mobile Facebook SDK for example, and then post that Facebook access_token to Feathers to do it's thing via the FacebookTokenStrategy method.

eg. from react-native, I've just authenticated natively via the Facebook SDK, which has given me an access token:

```
app.authenticate({
   type: 'token',
   endpoint: '/auth/facebook',
   access_token: accessToken
});
```

### CODE REVIEW

**Comment by marshallswain** [comment]
This looks good to me.  Do you mind making a PR for the docs and we can merge them both at the same time?

**Comment by mcnamee** [comment]
No problem @marshallswain - I've just submitted a PR. Hope it's ok :)

**Comment by mcnamee** [comment]
I've also added a `catch` for when an auth error occurs. Without this update, the script always continues as successful regardless of whether an error occurred. Now the client can show an error message etc.

**Comment by daffl** [comment]
I think this looks great, thank you @mcnamee! Looks like JSHint is failing on CI at the moment (`src/client/index.js: line 54, col 8, Missing semicolon.`).

**Comment by mcnamee** [comment]
@daffl - sorry for wasting your time, I should have tested sooner!

**Comment by daffl** [comment]
No worries. Thanks a lot for the PR! Released in 0.7.10

**Pull request merged**
