### PR TITLE
Validate if provider

### PR DESCRIPTION
**Pull request by mastertinner**
fix some hooks to not fire if the request is internal

### CODE REVIEW

**Comment by marshallswain** [comment]
For `queryWithUserId`, it would probably be better to remove the `else` and error throwing, which would remove the need for a provider check, I think.  That way, if a `hook.params.user` is in place, it will automatically add it.  Then it isn't duplicating functionality from the `requireAuth` hook, but works with it.  Here's an example that uses some of the new hooks in the upcoming OAuth release:

```
messageService.before({
  find: [
    authHooks.verifyToken({secret: 'feathers-rocks'}),
    authHooks.populateUser(),
    authHooks.requireAuth(),
    authHooks.queryWithUserId()
  ]
});
```

**Comment by marshallswain** [comment]
I think the same could be said for `restrictToSelf` and `setUserId`.  Thanks for your help!

**Comment by mastertinner** [comment]
thanks for your feedback, @marshallswain! i adapted the PR accordingly.

**Comment by daffl** [comment]
@marshallswain Good to go? We can merge it. There may be some conflicts with the decoupling branch by @ekryski but I don't think the hooks changed too much.

@mastertinner Thank you for contributing!

**Comment by ekryski** [comment]
:+1: Ya we can merge this stuff. I did make a couple changes to hooks but I'll sort out the conflicts.

Mad props to @mastertinner for his help! :boom:

**Comment by marshallswain** [comment]
Thanks for taking care of this, y'all.  I'm a little spread thin right now.  :)
Thanks @mastertinner for your help.

**Comment by mastertinner** [comment]
thanks for the support, guys!

**Pull request merged**
