### PR TITLE
Fix crash when no entityService is defined

### LINKED ISSUE #526: Server crashes when authenticating with Socket.io transport and no user entity service exists
### Steps to reproduce

1. Create a FeathersJS app which authenticates as follows:
    * Authenticate with feathers-authentication-jwt
    * Do NOT provide a users service, and leave `authentication.service` and `authentication.path` blank in the config file
    * Pass feathers-authentication-jwt a custom verifier that does not rely on any users service
2. Create a FeathersJS client which authenticates as follows:
    * Authenticate with feathers-authentication-client
    * Use the feathers-socketio client transport
3. Attempt to authenticate from the browser client with the `jwt` strategy

### Expected behavior
A connection should be established and authenticated

### Actual behavior
The server crashes with the following error:

```
  feathers-socket-commons:methods Setting up socket listener for event '58e2a3047463f61e5de6dbd6/api/storage::find' +0ms
  feathers-socket-commons:methods Setting up socket listener for event '58e2a3047463f61e5de6dbd6/api/storage::get' +0ms
  feathers-socket-commons:methods Setting up socket listener for event '58e2a3047463f61e5de6dbd6/api/storage::create' +0ms
  feathers-socket-commons:methods Setting up socket listener for event '58e2a3047463f61e5de6dbd6/api/storage::update' +0ms
  feathers-socket-commons:methods Setting up socket listener for event '58e2a3047463f61e5de6dbd6/api/storage::patch' +0ms
  feathers-socket-commons:methods Setting up socket listener for event '58e2a3047463f61e5de6dbd6/api/storage::remove' +0ms
  feathers-socket-commons:methods Setting up socket listener for event '58e2a3047463f61e5de6dbd6/api/authentication::create' +1ms
  feathers-socket-commons:methods Setting up socket listener for event '58e2a3047463f61e5de6dbd6/api/authentication::remove' +0ms
  feathers-socket-commons:methods Setting up socket listener for event '58e2a3047463f61e5de6dbd6/api/config::find' +0ms
  feathers-socket-commons:methods Setting up socket listener for event '58e2a3047463f61e5de6dbd6/api/events::find' +0ms
  feathers-socket-commons:methods Setting up socket listener for event '58e2a3047463f61e5de6dbd6/api/events::get' +0ms
  feathers-socket-commons:methods Setting up socket listener for event '58e2a3047463f61e5de6dbd6/api/events::create' +0ms
  feathers-socket-commons:methods Setting up socket listener for event '58e2a3047463f61e5de6dbd6/api/events::update' +0ms
  feathers-socket-commons:methods Setting up socket listener for event '58e2a3047463f61e5de6dbd6/api/events::patch' +0ms
  feathers-socket-commons:methods Setting up socket listener for event '58e2a3047463f61e5de6dbd6/api/events::remove' +0ms
  feathers-socket-commons:methods Setting up socket listener for event '58e2a3047463f61e5de6dbd6/api/availability::find' +1ms
  feathers-socket-commons:methods Setting up socket listener for event '58e2a3047463f61e5de6dbd6/api/availability::create' +0ms
/Users/jhill/Development/livescheduler/node_modules/feathers-authentication/lib/socket/handler.js:193
      entityService.on('updated', _updateEntity2.default);
                   ^

TypeError: Cannot read property 'on' of undefined
    at Namespace.<anonymous> (/Users/jhill/Development/livescheduler/node_modules/feathers-authentication/lib/socket/handler.js:193:20)
    at emitOne (events.js:101:20)
    at Namespace.emit (events.js:191:7)
    at Namespace.emit (/Users/jhill/Development/livescheduler/node_modules/socket.io/lib/namespace.js:212:10)
    at /Users/jhill/Development/livescheduler/node_modules/socket.io/lib/namespace.js:180:14
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### System configuration

**Module versions**:

- feathers v2.1.3
- feathers-authentication v1.2.4
- feathers-authentication-client v0.3.2
- feathers-authentication-hooks v0.1.4
- feathers-authentication-jwt v0.3.1
- feathers-hooks v2.0.1
- feathers-socketio v2.0.0
- socket.io-client v2.0.3

**NodeJS version**: v7.9.0

**Operating System**: Mac OS X

**Browser Version**: Chrome v58.0.3029.110 (64-bit)

**Module Loader**: Webpack v2.2.1

### PR DESCRIPTION
**Pull request by compwright**
Resolves #526

### CODE REVIEW

**Comment by daffl** [comment]
Thank you for the fix. I don't see how everything else is supposed to work if there is no entity service though?

**Comment by compwright** [comment]
It is perfectly possible if you use a custom verifier on the server side. Best I can tell it is only used here to grab the full user record using the id in the subject claim, but I don't need to do that.

**Comment by marshallswain** [comment]
@compwright do you feel like you're able to add a test for this?

**Comment by compwright** [comment]
@marshallswain probably, but this change lands in one of the few files that do not currently have any tests at all, so it's going to be a little involved.

**Comment by ekryski** [comment]
@compwright yup totally makes sense. We will definitely need a test here. We don't have unit tests for this file but do have functional tests. I think you could add some tests [here](https://github.com/feathersjs/feathers-authentication/blob/master/test/socket/update-entity.test.js)

This is power user functionality so to help out people that are new we should also add a console warning. If someone forgets to specify a service or fat fingers a service name we'd like to point that out because with this change auth won't work as but does not fail.

**Comment by compwright** [comment]
Makes sense. I'll add a helpful warning if the service value is omitted, and I'll suppress the warning if service is explicitly set to `false`. Thanks for the feedback. I'll attempt a test, too.

**Comment by ekryski** [comment]
@compwright any update on this? This is the first request we have had for this so if you need the functionality we'll need your help wrapping up the PR. Let us know if you are having trouble.

If it's not going to happen then we'll close out the PR and corresponding issue to keep things triaged and current. 🍻

**Comment by ekryski** [comment]
We've added checks in the `feathers-authentication-local`, `feathers-authentication-oauth1`, `feathers-authentication-oauth2` to toss an error if the entity service or it's `id` are undefined. That should cover this warning case.

We're going to be addressing this in a different way in the next version of Auth right around the corner when we make the authentication service and actual service and make it more transport agnostic.

Thanks for the PR and thought, but we're going to close this. You can follow progress of the auth update [here](https://github.com/feathersjs/feathers-authentication/projects).

**Pull request closed without merging**
