### PR TITLE
Fix toLowerCase hook

### LINKED ISSUE #74: Fix toLowerCase hook
There is a camelcased mistake in [src/hooks/to-lower-case.js (line 15)](https://github.com/feathersjs/feathers-authentication/blob/master/src/hooks/to-lower-case.js#L15):

```javascript
// src/hooks/to-lower-case.js (line 15)
 if (obj[fieldName] && obj[fieldName].toLowercase) {
```

__toLowercase__ isn't a method of String prototype: but __toLowerCase__ is (thanks captain obvious!)

Do you want me to do a PR?
or can you fix and release that mistake quickly?

Thanks a lot for your great work!

### PR DESCRIPTION
**Pull request by enten**
PR to fix #74  issue

### CODE REVIEW

**Comment by marshallswain** [comment]
Thanks!  Can you fix the one on line 7, too?

https://github.com/feathersjs/feathers-authentication/pull/75/files#diff-5c3a88f39327f1c9056093a30b1638aaR7

**Comment by enten** [comment]
done!

**Comment by marshallswain** [comment]
Cool.  One more thing I missed, can you revert the version number bump?  Our npm release scripts will take care of that.

**Comment by enten** [comment]
done too!

but __0.3.1__ it's still into [README changelog](https://github.com/enten/feathers-authentication/blob/cef36bd3b196424ea15340ed25fd92b448bcd8dd/README.md#changelog). have you a script to bump changelog?

**Comment by daffl** [comment]
Updating the changelog is fine.

@marshallswain It looks like there are no tests for this hook correct?

**Comment by marshallswain** [comment]
Correct.  I just checked.  That one is untested.

**Comment by ekryski** [comment]
Ya I'll add some tests today but that is a good fix. Thanks @enten! It's been on my list in auth repo but I haven't had time to get around to it. Honestly, wasn't sure if anyone would use that hook.

**Comment by enten** [comment]
Thanks!

I thinks that is it a great helper for fields with an unicity constraint (like username or email).

**Pull request merged**
